DROP TABLE take
/
DROP TABLE student
/
DROP TABLE course
/
CREATE TABLE student(
sid VARCHAR(30) NOT NULL,
sname VARCHAR(50) NOT NULL,
major VARCHAR(30) NOT NULL,
age INTEGER NOT NULL,
CONSTRAINT sid_pk PRIMARY KEY(sid));

CREATE TABLE course(
cno VARCHAR(30) NOT NULL,
cname VARCHAR(50) NOT NULL,
dept VARCHAR(30) NOT NULL,
credits INTEGER NOT NULL,
CONSTRAINT cno_pk PRIMARY KEY(cno));

CREATE TABLE take(
sid VARCHAR(30) NOT NULL,
cno VARCHAR(30) NOT NULL,
grade VARCHAR(30) NOT NULL,
PRIMARY KEY(sid,cno),
FOREIGN KEY(sid) REFERENCES student(sid),
FOREIGN KEY(cno) REFERENCES course(cno));

